#!/usr/bin/env python3
"""Regenerate native/snapshots_data.c from snapshots/m*.rle.gz."""
import os, glob
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
files = sorted(glob.glob(os.path.join(root, 'snapshots', 'm*.rle.gz')))
blob = bytearray(); offs = [0]; mins = []
for f in files:
    blob += open(f, 'rb').read(); offs.append(len(blob)); mins.append(int(os.path.basename(f)[1:].split('.')[0]))
with open(os.path.join(root, 'native', 'snapshots_data.c'), 'w') as out:
    out.write("// Generated by tools/gen-snapshot-data.py: gzip'd RLE snapshots of clock.rle, one per 10 minutes.\n#include <stddef.h>\n")
    out.write(f'const int SNAP_COUNT = {len(files)};\n')
    out.write('const int SNAP_MINUTE[] = {' + ','.join(map(str, mins)) + '};\n')
    out.write('const size_t SNAP_OFF[] = {' + ','.join(map(str, offs)) + '};\n')
    out.write('const unsigned char SNAP_DATA[] = {\n')
    for i in range(0, len(blob), 32):
        out.write(','.join(str(b) for b in blob[i:i + 32]) + ',\n')
    out.write('};\n')
print(f'{len(files)} snapshots, {len(blob) / 1e6:.1f} MB')
